version: '3'

services:
  back:
    env_file:
      - ".env"
    build:
      context: back
      dockerfile: Dockerfile
    container_name: cnd_video_test_task_back
    environment:
      - GEOCODING_API_KEY=${GEOCODING_API_KEY}
    command: >
      sh -c "python manage.py migrate && exec python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
